version: "3.5"

services:

  frontend:
    container_name: space_fiction_frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - space


  backend:
    container_name: space_fiction_backend
    build: ./backend
    env_file:
      - ./backend/.development.env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - space

  postgres:
    container_name: space_fiction_database
    image: postgres:15.3-alpine
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.development.env
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - space

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - space

  minio:
    container_name: space_fiction_storage
    image: minio/minio
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    restart: unless-stopped
    networks:
      - space
    ports:
      - "9001:9001"
      - "9090:9090"
    command: server ~/data --address ":9000" --console-address ":9090"


networks:
  space:
    external: true
