import React from 'react';
import Head from 'next/head';

const PageHeader = () => {
    return (
        <Head>
            <title>Space Fiction</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
    );
};

export default PageHeader;
